from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol

from simple_health_checker.models import CheckResult, EventLog, Monitor, MonitorState


class MonitorRepository(Protocol):
    async def initialize(self) -> None: ...

    async def close(self) -> None: ...

    async def list_monitors(self) -> list[Monitor]: ...

    async def list_monitors_with_states(self) -> list[tuple[Monitor, MonitorState]]: ...

    async def get_monitor(self, monitor_id: int) -> Monitor | None: ...

    async def create_monitor(self, monitor: Monitor) -> Monitor: ...

    async def update_monitor(self, monitor: Monitor) -> Monitor: ...

    async def set_monitor_enabled(self, monitor_id: int, enabled: bool) -> None: ...

    async def delete_monitor(self, monitor_id: int) -> None: ...

    async def get_state(self, monitor_id: int) -> MonitorState: ...

    async def upsert_state(self, state: MonitorState) -> None: ...

    async def list_due_monitors(self) -> list[tuple[Monitor, MonitorState]]: ...

    async def insert_check_result(self, result: CheckResult) -> None: ...

    async def insert_event_log(self, event_log: EventLog) -> None: ...

    async def list_recent_events(self, monitor_id: int, limit: int = 10) -> Sequence[EventLog]: ...

    async def is_acl_admin(self, user_id: int) -> bool: ...

    async def list_acl_admins(self) -> list[int]: ...

    async def count_acl_admins(self) -> int: ...

    async def grant_acl_admin(self, user_id: int, granted_by: int) -> None: ...

    async def revoke_acl_admin(self, user_id: int, revoked_by: int) -> bool: ...
